# Makefile for Qualcomm vidc driver

vidc-objs += \
		core.o \
		int_bufs.o \
		common.o \
		vdec.o \
		vdec_ctrls.o \
		venc.o \
		venc_ctrls.o \
		mem.o \
		resources.o \
		load.o \
		hfi/venus/venus_hfi.o \
		hfi/hfi_msgs.o \
		hfi/hfi_cmds.o \
		hfi/hfi.o \

obj-$(CONFIG_MSM_VIDC_V4L2) += vidc.o
